### ISSUE TITLE
# TODO though being here would be very strange, at least log the error

### ISSUE THREAD

**Issue by aidanlister** [evonove/django-oauth-toolkit#206] opened 2015-03-20 05:04 UTC
I'm getting one of these every now and then ... what could it be from? RefreshToken being deleted incorrectly by the client?

**Comment by JockeTF** [comment] 2015-03-20 10:34
I'm having the same issue: https://gist.github.com/JockeTF/5ff08a98d408d3e2e771

**Comment by aidanlister** [comment] 2015-06-17 01:33
See also https://github.com/jpadilla/django-rest-framework-oauth/issues/9

**Comment by xleon** [comment] 2015-07-30 20:01
I´m having the very same problem. The exception throws a lot

**Comment by aidanlister** [comment] 2015-07-31 02:59
Perhaps this is the fault of a badly behaved client, in which case maybe we
should return 400 Bad Request?

**Comment by masci** [comment] 2015-07-31 07:52
I was able to reproduce the issue providing the `refresh_token` param while requesting an access token. This behaviour is allowed by oauthlib even if I think @aidanlister is right, the request is malformed (see also https://tools.ietf.org/html/rfc6749#section-5.2).

Since the matter is debatable, I won't file an issue on oauthlib but I think DOT should refuse to accomplish the request with a 400 instead of an assert - I'm working on it.

**Comment by masci** [comment] 2015-07-31 08:40
On a second thought, this is something should stay in oauthlib. This is somehow confirmed by how difficult is returning a 400 in such a situation from within DOT.

**Comment by pySilver** [comment] 2015-10-09 18:18
@masci logically, yes it should stay in oauthlib, but technically it's easier to validate request in DOT

**Comment by pySilver** [comment] 2015-10-26 23:48
@masci this error also happens because of race condition. Two queries tries to update token using grant_type=refresh_token and passing refresh_token. First one succeeds, the other fails because RefreshToken.token has been changed and yet could not be revoked.

I suggest just ignore DoesNotExist error here. What disadvantages it may have?

**Comment by aidanlister** [comment] 2015-10-27 03:31
I'd love to not see this error in our logs 100 times every day

**Comment by xleon** [comment] 2015-10-27 18:04
@aidanlister +1

**Comment by pySilver** [comment] 2016-01-10 22:50
appears not be fixed yet.

**Comment by gbataille** [comment] 2016-08-02 11:43
@aidanlister  +1

**Comment by coderbounty-cowboy** [comment] 2016-12-04 20:35
Maybe consider putting a bounty on this? www.coderbounty.com

**Comment by synasius** [comment] 2016-12-05 08:29
Should be solved in #389 that it's merged

**Closed by synasius** 2016-12-05 08:29 UTC
