### ISSUE TITLE
Getting user object from Token

### ISSUE THREAD

**Issue by raphaeltorres** [evonove/django-oauth-toolkit#260] opened 2015-06-23 03:21 UTC
Is there a way to get the user id of the user who passes the token? Thanks!

**Comment by mattaustin** [comment] 2015-09-24 08:41
Possible duplicate of #194 ?

**Comment by masci** [comment] 2015-09-26 15:52
Do you mean, get it back in a response? Or while processing the request?
User instance is stored in `request.user`, if you clients need it, you should provide it through a  proper endpoint.

**Closed** 2016-03-17 15:56 UTC
