### ISSUE TITLE
Unable to omit client_secret from token revocation request

### ISSUE THREAD

**Issue by YPCrumble** [evonove/django-oauth-toolkit#474] opened 2017-05-11 14:53 UTC
First, thanks all for creating and maintaining this library!

This issue is related to #244 and others that are closed but I feel I am still experiencing the same issue.

I'm creating an application with the following settings:

Client ID: clientidstring
Client secret: <empty>
Client type: confidential
Authorization grant type: password

If I use the following [CURL request from the docs](https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_04.html#setup-a-request):

    curl --data "token=tokenstring&client_id=clientidstring" http://localhost:8000/o/revoke_token/

I get `{ 'error': 'invalid_client' }` (401 Unauthorized). However, if I use the following which adds an empty `client_secret` parameter the revocation succeeds:

    curl --data "token=tokenstring&client_id=clientidstring&client_secret=" http://localhost:8000/o/revoke_token/

Is this expected behavior? My thought is that based on the comments in other issues, completely omitting `client_secret` should be fine. 

I understand this is an issue with the oauthlib `Server`, not this repo. However, it seems like it's something that keeps coming up here in issues. I'd be happy to submit a PR to this repo whereby if `client_secret` is completely omitted we pass an empty `client_secret` parameter in its place. I imagine this would solve the issue for most users expecting to be able to completely omit the `client_secret` parameter. 

Or, am I perhaps missing something in my implementation that is causing this bug?

Thanks for any help!

**Comment by poswald** [comment] 2017-05-31 08:24
By my reading of the revocation RFC, the revoke request params is treated separately from the authorization.

To me it looks like you're saying you have a client with a confidential but blank secret. When you make your request, in the first one you're effectively saying "no client secret" but there is one... and it's blank.

Normally with a `password` grant type [you don't need to specify the client/client_secret](https://tools.ietf.org/html/rfc6749#section-4.3.2). If you do, then the server has to validate it. If the client is confidential the server also has to validate it. It can't do that if you don't pass it. If you happen to pass it as blank, then it works because you set the client secret to be blank.

Closing because I think it's "as designed" but reopen or maybe ask on the discussion forum if you don't agree? Maybe try to write a test case in this project to demonstrate it... sometimes the act of writing the test case helps me understand the flaw in my thinking.

**Closed by poswald** 2017-05-31 08:24 UTC
Labels: question

**Comment by YPCrumble** [comment] 2017-06-01 21:22
@poswald I'm actually not saying that "I have a client with a confidential but blank secret" (or at least I don't think I am). The issue is with the form. It has a space for client secret but if I don't put anything there, it saves a "blank secret" as you're suggesting. How would I create the application via that GUI with an "unspecified" or `null` client secret? That's what I'm trying to do by leaving that form blank. 

If leaving that field blank does create a `null` client secret, then my original question still stands - I have implemented a null client secret but the curl request is still requiring me to pass the parameter like `...client_secret="`

Does that clarify at all?

**Comment by poswald** [comment] 2017-06-06 02:46
In Django, a NULL string field isn't recommended and a blank one is considered the same thing so that's to be expected.

I think the problem is that if you are specifying the client is confidential, then according to the spec it has to try to verify the client secret. In resource owner/password auth, you basically are using the user's credentials to authenticate. The client is either public, or private (with a secret):

> The authorization server MUST:
> 
>    o  require client authentication for confidential clients or for any
>       client that was issued client credentials (or with other
>       authentication requirements),
> 
>    o  authenticate the client if client authentication is included, and
> 
>    o  validate the resource owner password credentials using its
>       existing password validation algorithm.
> 
>    Since this access token request utilizes the resource owner's
>    password, the authorization server MUST protect the endpoint against
>    brute force attacks (e.g., using rate-limitation or generating
>    alerts).

So... I think if you're using the resource owner grant type, then the client is either confidential and the client/secret _must_ be verified -or- the client is public and it's basically there as a purely informational user-agent type of thing since you can't _really_ prevent someone from spoofing it.
